#ifndef GLSL_UTILS
#define GLSL_UTILS

mat3 formBasis(vec3 n)
{
    mat3 R;
    vec3 T, B;
    if(n.z < -0.9999999f)
    {
        T = vec3( 0.0, -1.0, 0.0);
        B = vec3(-1.0,  0.0, 0.0);
    }
    const float a = 1.0f / (1.0f + n.z);
    const float b = -n.x * n.y * a;
    b1 = vec3(1.0f - n.x * n.x * a, b, -n.x);
    b2 = vec3(b, 1.0f - n.y*n.y*a, -n.y);

    R[0] = T;
    R[1] = B;
    R[2] = n;
    return R;
}












#endif